name: Pull Request Check
on:
  pull_request:
    paths:
      - common/**
      - fabric/**
      - forge/**
      - build.gradle
      - gradle.properties
      - settings.gradle

jobs:
  gametest:
    secrets: inherit
    uses: ./.github/workflows/gametest.yml
  build:
    runs-on: ubuntu-latest
    needs:
      - gametest
    env:
      CI_BUILD: true
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3.6.0
        with:
          distribution: zulu
          java-version: 17

      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build
        run: ./gradlew build

      - name: Read Properties
        id: 'properties'
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: gradle.properties
          properties: 'mod_id mod_name'

      - name: Get Version
        id: version
        run: |
          MESSAGE=$(ls forge/build/libs/* | grep sources.jar -v | grep shadow.jar -v | grep slim.jar -v | awk -F '${{ steps.properties.outputs.mod_id }}-forge-|.jar' '{print $2}')
          echo "version=$MESSAGE" >> $GITHUB_OUTPUT

      - name: capture build artifacts
        uses: actions/upload-artifact@v4.3.3
        with:
          name: "${{ steps.properties.outputs.mod_name }} ${{ steps.version.outputs.version }}"
          path: |
            fabric/build/libs/anvilcraft-fabric-${{ steps.version.outputs.version }}.jar
            forge/build/libs/anvilcraft-forge-${{ steps.version.outputs.version }}.jar
